---
apiVersion: v1
kind: Service
metadata:
  name: swagger
  namespace: testing
  labels:
    app: swagger
spec:
  selector:
    app: swagger
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
