# Dynamically generated file, please do not manually edit it.

# Gateway TOML definition.

[alfa]

name = "Alfa service"
short_name = "alfa"

[alfa.owner]
name = "Luigi Riefolo"
date_created = "2017-08-27T10:30:00+01:00"

[alfa.server]
host = "localhost"
port = 10101
is_gateway = true
gateway_port = 10100
services = [ "alfa", "beta" ]

[alfa.database]
server = "localhost"
ports = [ 8001, 8001, 8002 ]
connection_max = 5000


# Beta service TOML definition.

[beta]

name= "Beta service"
short_name = "beta"

[beta.owner]
name = "Luigi Riefolo"
date_created = "2017-08-27T10:30:00+01:00"

[beta.server]
host = "localhost"
port = 10102
clients = [ "omega" ]

[beta.database]
server = "localhost"
ports = [ 8001, 8001, 8002 ]
connection_max = 5000


# Omega service TOML definition.

[omega]

name = "Omega service"
short_name = "omega"

[omega.owner]
name = "Luigi Riefolo"
date_created = "2017-08-27T10:30:00+01:00"

[omega.server]
host = "localhost"
port = 10103
clients = [ "beta" ]
services = [ "omega" ]

[omega.database]
server = "localhost"
ports = [ 8001, 8001, 8002 ]
connection_max = 5000


