apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: alfa
spec:
  replicas: 3
  selector:
    matchLabels:
      app: alfa
  template:
    metadata:
      labels:
        app: alfa
    spec:
      containers:
        - name: alfa
          image: localhost:5000/alfa:v1
          ports:
            - name: http
              containerPort: 8080
      imagePullSecrets:
      - name: secret64
