// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gateway.proto

/*
Package gateway is a generated protocol buffer package.

It is generated from these files:
	gateway.proto

It has these top-level messages:
	Message
*/
package gateway

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import google_protobuf1 "github.com/golang/protobuf/ptypes/empty"
import alfa "github.com/luigi-riefolo/eGO/src/alfa/pb"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Message represents a simple message sent to the Gateway service.
type Message struct {
	// Id represents the message identifier.
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// The message to be sent.
	Msg string `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Message) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Message) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*Message)(nil), "gateway.Message")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Gateway service

type GatewayClient interface {
	// Get method receives a simple message and returns it.
	// The message posted as the id parameter will also be returned.
	Get(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*Message, error)
	// Gateway method sets a simple message.
	Set(ctx context.Context, in *Message, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	Test(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*alfa.Message, error)
}

type gatewayClient struct {
	cc *grpc.ClientConn
}

func NewGatewayClient(cc *grpc.ClientConn) GatewayClient {
	return &gatewayClient{cc}
}

func (c *gatewayClient) Get(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := grpc.Invoke(ctx, "/gateway.Gateway/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) Set(ctx context.Context, in *Message, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/gateway.Gateway/Set", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) Test(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*alfa.Message, error) {
	out := new(alfa.Message)
	err := grpc.Invoke(ctx, "/gateway.Gateway/Test", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Gateway service

type GatewayServer interface {
	// Get method receives a simple message and returns it.
	// The message posted as the id parameter will also be returned.
	Get(context.Context, *google_protobuf1.Empty) (*Message, error)
	// Gateway method sets a simple message.
	Set(context.Context, *Message) (*google_protobuf1.Empty, error)
	Test(context.Context, *google_protobuf1.Empty) (*alfa.Message, error)
}

func RegisterGatewayServer(s *grpc.Server, srv GatewayServer) {
	s.RegisterService(&_Gateway_serviceDesc, srv)
}

func _Gateway_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf1.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gateway.Gateway/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).Get(ctx, req.(*google_protobuf1.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gateway.Gateway/Set",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).Set(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_Test_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf1.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).Test(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gateway.Gateway/Test",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).Test(ctx, req.(*google_protobuf1.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Gateway_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gateway.Gateway",
	HandlerType: (*GatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Gateway_Get_Handler,
		},
		{
			MethodName: "Set",
			Handler:    _Gateway_Set_Handler,
		},
		{
			MethodName: "Test",
			Handler:    _Gateway_Test_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gateway.proto",
}

func init() { proto.RegisterFile("gateway.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 286 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xcd, 0x4a, 0xf4, 0x30,
	0x14, 0x86, 0x69, 0xfb, 0xf1, 0x95, 0x09, 0x76, 0x1c, 0x0f, 0xfe, 0x0c, 0xd5, 0x85, 0x74, 0x25,
	0x8a, 0x09, 0x3a, 0x3b, 0x97, 0xe2, 0x50, 0x37, 0x22, 0xa8, 0x2b, 0x77, 0xe9, 0xcc, 0x69, 0x0c,
	0xb4, 0x4d, 0x69, 0x4e, 0x15, 0xb7, 0xde, 0x82, 0x97, 0xe6, 0x0d, 0xb8, 0xf0, 0x42, 0x64, 0xd2,
	0x56, 0x17, 0x32, 0xab, 0xe4, 0x24, 0x6f, 0x1e, 0x9e, 0x97, 0xb0, 0x48, 0x49, 0xc2, 0x17, 0xf9,
	0xca, 0xeb, 0xc6, 0x90, 0x81, 0xb0, 0x1f, 0xe3, 0x03, 0x65, 0x8c, 0x2a, 0x50, 0xc8, 0x5a, 0x0b,
	0x59, 0x55, 0x86, 0x24, 0x69, 0x53, 0xd9, 0x2e, 0x16, 0xef, 0xf7, 0xb7, 0x6e, 0xca, 0xda, 0x5c,
	0x60, 0x59, 0x53, 0xcf, 0x88, 0x67, 0x4a, 0xd3, 0x53, 0x9b, 0xf1, 0x85, 0x29, 0x45, 0xd1, 0x6a,
	0xa5, 0x4f, 0x1b, 0x8d, 0xb9, 0x29, 0x8c, 0xc0, 0xf4, 0x56, 0xd8, 0x66, 0x21, 0x64, 0x91, 0x4b,
	0x51, 0x67, 0x6e, 0xed, 0x1e, 0x25, 0x27, 0x2c, 0xbc, 0x41, 0x6b, 0xa5, 0x42, 0x18, 0x33, 0x5f,
	0x2f, 0xa7, 0xde, 0xa1, 0x77, 0x34, 0xba, 0xf3, 0xf5, 0x12, 0x26, 0x2c, 0x28, 0xad, 0x9a, 0xfa,
	0xee, 0x60, 0xb5, 0x3d, 0xff, 0xf4, 0x58, 0x98, 0x76, 0xa2, 0x30, 0x67, 0x41, 0x8a, 0x04, 0xbb,
	0xbc, 0x53, 0xe2, 0x83, 0x12, 0x9f, 0xaf, 0x94, 0xe2, 0x09, 0x1f, 0x0a, 0xf6, 0xf8, 0x64, 0xfb,
	0xed, 0xe3, 0xeb, 0xdd, 0x1f, 0xc3, 0x86, 0x78, 0x3e, 0xeb, 0x4c, 0x14, 0x12, 0x5c, 0xb3, 0xe0,
	0x1e, 0x09, 0xfe, 0xc4, 0xe3, 0x35, 0xe0, 0x64, 0xcf, 0x61, 0xb6, 0x92, 0x5f, 0x8c, 0x45, 0xba,
	0xf0, 0x8e, 0xe1, 0x8a, 0xfd, 0x7b, 0x40, 0xbb, 0xde, 0x28, 0xe2, 0xae, 0xf6, 0xa0, 0xb3, 0xe3,
	0x38, 0x9b, 0x10, 0xfd, 0x70, 0x08, 0x2d, 0x5d, 0x8e, 0x1e, 0x87, 0xaf, 0xc8, 0xfe, 0x3b, 0xc0,
	0xec, 0x3b, 0x00, 0x00, 0xff, 0xff, 0xdd, 0xc2, 0xce, 0x42, 0xab, 0x01, 0x00, 0x00,
}
