apiVersion: v1
kind: Service
metadata:
  name: omega
  labels:
    app: omega
spec:
  type: LoadBalancer
  selector:
    app: omega
  ports:
  - name: omega-service
    protocol: TCP
    port: 10103
    targetPort: 10103
  - name: prometheus
    protocol: TCP
    port: 8080
