apiVersion: apps/v1alfa1
kind: Deployment
metadata:
  name: omega
spec:
  replicas: 3
  selector:
    matchLabels:
      app: omega
  template:
    metadata:
      labels:
        app: omega
    spec:
      containers:
        - name: omega
          image: localhost:5000/omega:v1
          ports:
            - name: omega-service
              containerPort: 10103
            - name: prometheus
              containerPort: 8080
      imagePullSecrets:
      - name: secret64
