apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  type: LoadBalancer
  selector:
    app: gateway
  ports:
  - name: gateway-service
    protocol: TCP
    port: 10100
    targetPort: 10100
  - name: prometheus
    protocol: TCP
    port: 8080
