---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-server-conf
  labels:
    name: grafana
  namespace: monitoring
data:
  prometheus-datasource.json: |
    {
      "name": "prometheus",
      "type": "prometheus",
      "url": "http://192.168.64.7:30500",
      "access": "proxy",
      "basicAuth": false
    }
